#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SYMBOL_DIR = path.resolve(__dirname, "../white/small");
const OUT_FILE = path.resolve(__dirname, "symbols.ts");

/** App export name → SF Symbol file stem (without .svg) */
const MANIFEST = {
  play: "play",
  pause: "pause",
  "forward.end": "forward.end",
  "backward.end": "backward.end",
  house: "house",
  "antenna.radiowaves.left.and.right": "antenna.radiowaves.left.and.right",
  map: "map",
  "music.note.house": "music.note.house",
  magnifyingglass: "magnifyingglass",
  xmark: "xmark",
  "chevron.left": "chevron.left",
  "chevron.right": "chevron.right",
  ellipsis: "ellipsis",
  star: "star",
  "list.bullet": "list.bullet",
  "quote.bubble": "quote.bubble",
  plus: "plus",
  "square.grid.2x2": "square.grid.2x2",
  "list.dash": "list.dash",
  heart: "heart",
  shuffle: "shuffle",
  repeat: "repeat",
  "repeat.1": "repeat.1",
  microphone: "microphone",
  "square.and.arrow.up": "square.and.arrow.up",
  "square.and.arrow.down": "square.and.arrow.down",
  "music.note.list": "music.note.list",
  link: "link",
  gearshape: "gearshape",
  "person.2": "person.2",
  shield: "shield",
  info: "info",
  "arrow.right": "arrow.right",
  creditcard: "creditcard",
  "questionmark.circle.dashed": "questionmark.circle.dashed",
  "rectangle.portrait.and.arrow.right": "rectangle.portrait.and.arrow.right",
  checkmark: "checkmark",
};

function parseSvg(filePath) {
  const xml = fs.readFileSync(filePath, "utf8");
  const viewBox = xml.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`No viewBox in ${filePath}`);

  const paths = [...xml.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`No paths in ${filePath}`);

  return { viewBox, paths };
}

const symbols = {};
for (const [name, stem] of Object.entries(MANIFEST)) {
  const filePath = path.join(SYMBOL_DIR, `${stem}.svg`);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing symbol: ${filePath}`);
  }
  symbols[name] = parseSvg(filePath);
}

const lines = [
  "// Generated by react/generate.mjs — do not edit by hand.",
  "",
  "export type SymbolName =",
  `  ${Object.keys(symbols).map((k) => JSON.stringify(k)).join(" |\n  ")};`,
  "",
  "export const SYMBOLS: Record<SymbolName, { viewBox: string; paths: string[] }> =",
  JSON.stringify(symbols, null, 2) + " as const;",
  "",
];

fs.writeFileSync(OUT_FILE, lines.join("\n"));
console.log(`Wrote ${Object.keys(symbols).length} symbols → ${OUT_FILE}`);
